config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  root to: "member#profile"
  get 'meeting/:meeting_id/healthgoals', to: 'goal#index', as: 'meeting_healthgoals'
  get 'profile', to: 'member#profile'
  post 'update-goal', to: "goal#update_goal"
  post 'new-goal', to: "goal#new_goal"
  post 'add-credit', to: 'credit#add_credit'
  delete 'remove-credit', to: 'credit#remove_credit'
  delete 'delete-goal', to: "goal#delete_goal"
  post 'meeting/create', to: 'meeting#create'
  resources :meeting, only: ['new']
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :member
end

app/models/family.rb
class Family < ApplicationRecord
  has_many :members
  has_many :meetings

  def health_goals
    self.meetings.order(date: :desc).map do | meeting |
      {
        date: meeting[:date],
        goals: meeting.health_goals
      }
    end

  end
end

app/models/health_goal.rb
class HealthGoal < ApplicationRecord
  belongs_to :member
  has_one :meeting
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :family
  has_many :health_goals

  def filtered_health_goals 
    family.members.map do |member|
      {member_name: member.name, health_goals: health_goals.filter {|health_goal| health_goal.member_id = member.id} }
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :health_goals
  has_many :credits
  belongs_to :family

  def credits_for_member(member_id)
    credits.where(receiving_member_id: member_id).length
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

private

  def require_login
    unless current_member || request.path == "/members/sign_in"
      redirect_to "/members/sign_in"
    end
  end
end

app/controllers/credit_controller.rb
class CreditController < ApplicationController
  def add_credit
    Credit.create(member_id: params["memberId"], receiving_member_id: params["receivingMemberId"])
    render json: { count: Credit.where(member_id: params["memberId"], receiving_member_id: params["receivingMemberId"]).length }
  end
  def remove_credit
    credits = Credit.where(member_id: params["memberId"], receiving_member_id: params["receivingMemberId"])
    if credits.length > 0 
      credits.last.delete
    end
    render json: { count: Credit.where(member_id: params["memberId"], receiving_member_id: params["receivingMemberId"]).length }
  end
end

app/controllers/goal_controller.rb
class GoalController < ApplicationController
  def index
    family = Family.find(current_member[:family_id])
    @current_meeting_id = params[:meeting_id]
    meeting = Meeting.find(@current_meeting_id)
    @health_goals = family.health_goals
    @family_members = family.members 
    @meetings = family.meetings.map do | meeting |
      { id: meeting.id, date: meeting.date, health_goals: meeting.health_goals }    
    end
    @meetings = @meetings.reverse
  end

  def update_goal
    goal = HealthGoal.find(params["goalId"])
    res = goal.update( goal: params["inputValue"], status: params["goalStatus"] )
    render json: res
  end

  def new_goal
    res = HealthGoal.create( goal: params["inputValue"], status: params["goalStatus"], member_id: params["memberId"], meeting_id: params["meetingId"] )
    render json: res
  end

  def delete_goal
    res = HealthGoal.destroy(params["goal_id"])
    render json: res
  end
end

app/controllers/meeting_controller.rb
class MeetingController < ApplicationController
  def new

  end

  def create
    meeting = Meeting.create(family_id: current_member.family.id, date: Time.now )
    redirect_to "/meeting/#{meeting.id}/healthgoals"
  end


end

app/controllers/member_controller.rb
class MemberController < ApplicationController
  def register 
    render 'devise/registrations/new' 
  end

  def profile
    @current_member = current_member
    @current_family = @current_member.family
    @last_meeting = @current_family.meetings.sort_by(&:date).last  
  end
end

app/helpers/member_helper.rb
module MemberHelper
end

app/views/goal/_dashboard_input.html.erb
<div class = "column-container">
  <h2>
    <%= name %>
  </h2>
  <input class = "dashboard-goal-input" />
  <button class = "dashboard-goal-add" data-button-type = "addGoal" data-goal-target = '<%= goal_id %>' >+</button>
  <ul id = '<%= goal_id %>'>
  </ul>
</div>

app/views/goal/index.html.erb
<%= react_component("Dashboard", {current_meeting_id: @current_meeting_id, meetings: @meetings, health_goals: @health_goals, family_members: @family_members, csrf_token: session[:_csrf_token]}) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthWellnessComittee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>
  </head>

  <body>
    <%= render 'shared/header'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/meeting/new.html.erb
<%= form_with url: "/meeting/create", method: :post, class: "flex justify-center pt-28" do |form| %>
  <%= form.submit "New Meeting", class: "cursor-pointer text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
<% end %>

app/views/member/profile.html.haml
.container.m-8
  %div
    = "#{@current_member[:name]}, a member of #{@current_family[:name]}"
  = form_with url: "/meeting/create", method: :post do |form|
    = form.submit "New Meeting", class: "bg-transparent cursor-pointer text-indigo-700"
  %div
    = "Last #{link_to('meeting', meeting_healthgoals_path(@last_meeting.id), {class: 'text-indigo-700'}).html_safe} was #{@last_meeting[:created_at].strftime("%B %d %Y")}".html_safe
  %div
    Health Goals this week:
    %ul
    - @last_meeting.health_goals.where(member_id: @current_member.id).each do | g |
      %li
        = g.goal
  %ol Credits
  - @current_family.members.each do |m|
    - unless m.id == @current_member.id
      %li
        %span
          = "#{m[:name]}: "
        %span{id: "member-credit-count-#{m.id}"}        
          = @current_member.credits_for_member(m.id)
        %button.member_use_credit.bg-transparent.cursor-pointer.text-indigo-700{data: {member_id: @current_member.id, receiving_member_id: m.id}}
          Use Credit
        %button.member_add_credit.bg-transparent.cursor-pointer.text-indigo-700{data: {member_id: @current_member.id, receiving_member_id: m.id}}
          Add Credit

app/views/shared/_header.html.haml
%header.h-12.bg-indigo-700.w-full.flex.text-white.px-6.fixed.z-50
  .flex.items-center{class: 'w-10/12' }
    %h1 
      Family Meeting
  %div.flex.items-center.whitespace-nowrap
    %a.text-white{href: '/profile'}
      My Profile
.h-12